import Link from 'next/link'
import { SUPPORT_EMAIL } from '@/lib/storefront/legal'

export const metadata = {
  title: 'Privacy policy',
  description: 'How Housefinds handles customer, order, support and storefront data.',
}

const sections = [
  ['Information we use', 'When you shop with Housefinds we may process the details needed to run the store, including your name, delivery and billing address, email, telephone number when supplied, basket contents, order information, support messages and technical information generated by the storefront.'],
  ['Payments', 'Card details are entered into secure Stripe-hosted payment fields. Housefinds does not receive or store your full card number or card security code. We do receive the payment and order status information needed to process the purchase and support the order.'],
  ['Why we use this information', 'We use information to provide the storefront, maintain your basket, process and fulfil orders, communicate delivery and order updates, handle returns and customer support, prevent abuse, diagnose technical problems and meet legal or accounting obligations that apply to the transaction.'],
  ['Services that support the store', 'The customer-facing store is hosted separately from the WooCommerce commerce backend. Service providers involved in hosting, commerce, payment processing, delivery or support may process the minimum information they need to provide their service.'],
  ['Cookies and local storage', 'The store uses necessary browser storage and cookies for functions such as maintaining a secure cart session and restoring order information. Contact, delivery and billing details entered at checkout may be saved temporarily in this browser tab so you can resume your progress. The checkout restores a draft only when it relates to the same basket and was saved within the previous 30 minutes. A confirmed successful checkout clears that draft. Card numbers and security codes are never included in the draft. A separate pending-payment marker helps prevent a repeated payment attempt in the same tab when the previous result is uncertain. The storefront can also emit first-party measurement events for product views, searches, cart actions, checkout and completed purchases. External analytics or advertising tags should only be enabled when they have been separately configured and the required privacy controls are in place.'],
  ['Retention and security', 'We keep information for as long as it is reasonably needed for orders, support, fraud prevention, record keeping and legal obligations. We use technical and organisational safeguards appropriate to the service, but no internet service can promise absolute security.'],
  ['Your choices and rights', 'Depending on the law that applies to you, you may have rights relating to access, correction, deletion, restriction or objection. You can contact Housefinds to ask a privacy question or make a request. We may need enough information to verify that a request relates to you.'],
]

export default function PrivacyPolicyPage() {
  return (
    <main className="hf-page">
      <div className="hf-container max-w-[1120px] py-14 lg:py-20">
        <Link href="/" className="text-sm font-semibold text-[var(--hf-brand)] hover:underline">← Back to Housefinds</Link>
        <div className="mt-8 grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:gap-16">
          <div>
            <p className="hf-eyebrow text-[var(--hf-brand-muted)]">Privacy</p>
            <h1 className="mt-4 text-[clamp(3rem,5vw,5.4rem)] font-semibold leading-[.92] tracking-[-.06em] text-[var(--hf-ink)]">Clear about the data behind your order.</h1>
            <p className="hf-copy-lg mt-6 max-w-lg">This policy explains the information used by the Housefinds storefront and the services that support a purchase.</p>
            <div className="hf-panel mt-7 p-5 text-sm leading-6 text-black/58">
              Privacy contact<br /><a className="font-semibold text-[var(--hf-brand)] underline underline-offset-3" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>
            </div>
          </div>
          <div className="space-y-3">
            {sections.map(([title, copy]) => (
              <section key={title} className="hf-panel p-6 sm:p-7">
                <h2 className="text-xl font-semibold tracking-[-.03em]">{title}</h2>
                <p className="mt-3 text-sm leading-7 text-black/58">{copy}</p>
              </section>
            ))}
            <section className="hf-panel p-6 sm:p-7">
              <h2 className="text-xl font-semibold tracking-[-.03em]">Questions</h2>
              <p className="mt-3 text-sm leading-7 text-black/58">For a privacy question, contact <a className="font-semibold text-[var(--hf-brand)] underline underline-offset-3" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. For order tracking, use the <Link href="/track-order" className="font-semibold text-[var(--hf-brand)] underline underline-offset-3">order tracking page</Link>.</p>
            </section>
          </div>
        </div>
      </div>
    </main>
  )
}
